image: node:lts-alpine

stages:
  - test
  - deploy

cache:
  key: modules
  paths:
    - website/node_modules/

variables:
  URL: 'https://scgc.pages.upb.ro'
  BASE_URL: '/cloud-courses/'

test:
  stage: test
  cache:
    key: modules
    paths:
      - website/node_modules/
  script:
  - cd website
  - yarn install --audit
  - yarn build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  cache:
    key: modules
    paths:
      - website/node_modules/
  script:
  - cd website
  - yarn install --audit
  - yarn build
  - mv ./build ../public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
